{% set version = "8.1.1" %}
{% set build_number = 2 %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

{% set build_number = build_number + 200 %}   # [not VTK_WITH_OSMESA]

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 71a09b4340f0a9c58559fe946dc745ab68a866cf20636a41d97b6046cb736324

build:
  skip: True  # [win and py27]
  number: {{ build_number }}
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]
    - mesalib   # [VTK_WITH_OSMESA]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.8.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
    - tbb
    - mesalib   # [VTK_WITH_OSMESA]
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.*
    - freetype 2.8.*
    - hdf5 1.8.18|1.8.18.*  # [unix]
    - libxml2 2.9.*
    - libpng >=1.6.23,<1.7
    - jpeg 9*
    - libtiff 4.0.*
    - jsoncpp  # [unix]
    - expat
    - tbb
    - mesalib   # [VTK_WITH_OSMESA]

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
