{% set version = "9.0.1" %}
{% set build_number = 0 %}

{% set minor_version = ".".join(version.split(".")[:2]) %}

{% set build_number = build_number + 200 %}   # [not VTK_WITH_OSMESA]

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 1b39a5e191c282861e7af4101eaa8585969a2de05f5646c9199a161213a622c7
  patches:
    - 0001-Link-libpython-optionally-make-vtkPython-dep-compile.patch
    - 0002-VTKGenerateExportHeader-Prefer-dumpversion-over-vers.patch

build:
  skip: True  # [win and vc<14]
  number: {{ build_number }}
  features:
    - mesalib   # [VTK_WITH_OSMESA]
  ignore_run_exports:
    - libogg    # seems required to enable OGG support, but not actually linked to?

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja

requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
  {% if SUBDIR in ('linux-64', 'linux-32', 'linux-ppc64le', 'linux-aarch64') %}
    - {{ cdt('libxcb') }}
    - {{ cdt('libxau') }}
    - {{ cdt('libxau') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libxext') }}
    - {{ cdt('libxfixes') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libsm-devel') }}
    - {{ cdt('libxt-devel') }}
    - {{ cdt('libice-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('xorg-x11-proto-devel') }}
  {% endif %}
  host:
    - python
    # VTK Third Party dependencies
    - zlib
    # Limit freetype version to avoid compile errors triggered by freetype
    # >=2.10.3 no longer exporting `FT_CALLBACK_DEF`; for details, see:
    # <https://gitlab.kitware.com/vtk/vtk/-/issues/18033>
    - freetype <2.10.3
    - hdf5     # [unix]
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    # Limit TBB version. The oneAPI (2021.*) release removed the `tbb_stddef.h`
    # header, which causes configure-time errors. The 2020 release is probably
    # safe to use but generates *tons* of deprecation warnings that (may) hint
    # at subtle breaks. Given all that, we set the limit to the latest version
    # available when VTK 8.2 was released.
    - tbb <=2019
    - tbb-devel <=2019
    - mesalib   # [VTK_WITH_OSMESA]
    - libnetcdf
    - lz4-c
    - libogg      # [unix]
    - libtheora   # [unix]
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - mesalib   # [VTK_WITH_OSMESA]
    - jsoncpp
    # Upper bound set by the version we built with above; TBB 2021.0 removed
    # the needed `libtbb.so.2` DSO, and (may have) introduced API and/or ABI
    # compatibilities.
    - tbb <2021.0.0a0
    # Rest will be taken care of by run_exports

test:
  imports:
    - vtkmodules
    - vtkmodules.vtkChartsCore
    - vtkmodules.vtkCommonCore
    - vtkmodules.vtkFiltersCore
    - vtkmodules.vtkFiltersGeneric
    - vtkmodules.vtkGeovisCore
    - vtkmodules.vtkFiltersHybrid
    - vtkmodules.vtkIOCore
    - vtkmodules.vtkIOXdmf2
    - vtkmodules.vtkImagingCore
    - vtkmodules.vtkInfovisCore
    - vtkmodules.vtkRenderingCore
    - vtkmodules.vtkViewsCore
    - vtkmodules.vtkRenderingVolume
    - vtkmodules.vtkInteractionWidgets
  requires:
    - setuptools

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
