{% set version = "9.4.1" %}
{% set build_number = 0 %}

{% set major_minor = ".".join(version.split(".")[:2]) %}

{% set build_number = build_number + 200 %}   # [not VTK_WITH_OSMESA]

package:
  name: vtk
  version: {{ version }}

source:
  url: https://www.vtk.org/files/release/{{ major_minor }}/VTK-{{ version }}.tar.gz
  sha256: c253b0c8d002aaf98871c6d0cb76afc4936c301b72358a08d5f3f72ef8bc4529
  patches:
    - patches/fix-threads-windows.patch  # [win]
    # https://github.com/conda-forge/vtk-feedstock/pull/282
    # https://gitlab.kitware.com/vtk/vtk/-/issues/18365#note_1079278
    # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/9987
    - patches/9987_try_except_python_import.patch  # [not win]
    # https://gitlab.kitware.com/vtk/vtk/-/merge_requests/11486
    #- patches/11486.patch

build:
  skip: True  # [win32 or s390x or ppc64le]
  number: {{ build_number }}
  features:
    - mesalib   # [VTK_WITH_OSMESA]
  missing_dso_whitelist:
    - '*/ld-linux-*.so.*'
    - '*/libc.so.*'
    - '*/libdl.so.*'
    - '*/libm.so.*'
    - '*/libpthread.so.*'
    - '*/libvtk*.dylib'
  run_exports:
    - {{ pin_subpackage('vtk', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - patch  # [not win]
    - m2-patch  # [win]
    - pugixml
  {% if SUBDIR in ('linux-64', 'linux-32', 'linux-ppc64le', 'linux-aarch64') %}
    - {{ cdt('libxcb') }}
    - {{ cdt('libxau') }}
    - {{ cdt('libxau') }}
    - {{ cdt('libuuid') }}
    - {{ cdt('libxext') }}
    - {{ cdt('libxfixes') }}
    - {{ cdt('libxxf86vm') }}
    - {{ cdt('libxdamage') }}
    - {{ cdt('libselinux') }}
    - {{ cdt('libsm-devel') }}
    - {{ cdt('libxt-devel') }}
    - {{ cdt('libice-devel') }}
    - {{ cdt('libx11-devel') }}
    - {{ cdt('mesa-libgl-devel') }}
    - {{ cdt('mesa-dri-drivers') }}
    - {{ cdt('xorg-x11-proto-devel') }}
  {% endif %}
  host:
    - python
    # VTK Third Party dependencies
    - zlib
    - freetype 2.12
    - hdf5
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    # Limit TBB version. The oneAPI (2021.*) release removed the `tbb_stddef.h`
    # header, which causes configure-time errors. The 2020 release is probably
    # safe to use but generates *tons* of deprecation warnings that (may) hint
    # at subtle breaks. Given all that, we set the limit to the latest version
    # available when VTK 8.2 was released.
    - tbb
    - tbb-devel 2021.8.0
    - mesalib  # [VTK_WITH_OSMESA]
    - libnetcdf
    - lz4-c
    - boost-cpp
    - tk  # [not win and not VTK_WITH_OSMESA]
    - ffmpeg
    - utfcpp 3.2.1
    - eigen 3.3.7
    - double-conversion 3.1.5
    - pugixml
    - glew
    - libogg 1.3.5
    - libtheora
    - nlohmann_json
    - proj
    - loguru 0.5.3
    - sqlite
    - gl2ps
    # We have an (experimental?) Qt 6.1 build available on osx-arm64,
    # but for the sake of coherence, we pin to 5 across all variants.
    - qt-main =5
    - xz
  run:
    - python
    - zlib
    - freetype
    - hdf5
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - mesalib  # [VTK_WITH_OSMESA]
    - libnetcdf
    - lz4-c
    - tk  # [not win and not VTK_WITH_OSMESA]
    - ffmpeg
    - {{ pin_compatible('utfcpp') }}
    - {{ pin_compatible('eigen') }}
    - {{ pin_compatible('double-conversion') }}
    - glew
    - libogg
    - libtheora
    - proj
    - {{ pin_compatible('loguru') }}
    - sqlite
    - gl2ps
    # Not all our Qt builds in distribution seem to export a pinning.
    - {{ pin_compatible('qt') }}
    - xz

  run_constrained:
    # Paraview bundles its own VTK that has conflicting Python vtkmodules
    - paraview ==9999999999

test:
  requires:
    - setuptools
    - python

about:
  home: https://vtk.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: Copyright.txt
  summary: >
    VTK is an open-source software system designed for 3D computer graphics, image processing, 
    and visualization. It provides libraries and tools for developing scientific and 
    engineering applications that require 3D visualization.
  description: |
    VTK, or Visualization Toolkit, is an open-source software system designed for 3D computer graphics, 
    image processing, and visualization. It provides a wide range of libraries and tools that are useful 
    for developing scientific and engineering applications that require 3D visualization, such as medical 
    imaging, computational fluid dynamics, and data visualization. The package supports a wide range of 
    visualization algorithms and techniques, including volume rendering, isosurface extraction, contouring, 
    and glyphs. VTK is implemented in C++ with Python bindings, and includes pre-built classes and functions 
    for manipulating and visualizing data. The package has been used in various applications, including 
    medical imaging, computational fluid dynamics, molecular modeling, and geospatial data visualization.
  dev_url: https://gitlab.kitware.com/vtk/vtk
  doc_url: https://vtk.org/documentation/

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
