{% set version = "8.2.0" %}
{% set build_number = 0 %}
{% set release_candidate = ".rc2" %}


{% set minor_version = ".".join(version.split(".")[:2]) %}

{% set build_number = build_number + 200 %}   # [not VTK_WITH_OSMESA]

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}{{release_candidate}}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 8ac6ef780eef170d572bae13fe2e4d40ffe453a4986391e528390e8a325c7674

build:
  skip: True  # [win and py27]
  number: {{ build_number }}
  features:
    - mesalib   # [VTK_WITH_OSMESA]

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake
    - ninja
  host:
    - python
    # VTK Third Party dependencies
    - zlib
    - freetype
    - hdf5 1.10.1
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - tbb-devel
    - mesalib   # [VTK_WITH_OSMESA]
    - libnetcdf
    - lz4-c
    - libogg      # [unix]
    - libtheora   # [unix]
    - xorg-libxt  # [linux]
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib
    - freetype
    - hdf5 1.10.1
    - libxml2
    - libpng
    - jpeg
    - libtiff
    - jsoncpp
    - expat
    - tbb
    - mesalib   # [VTK_WITH_OSMESA]
    - libnetcdf
    - lz4-c
    - libogg      # [unix]
    - libtheora   # [unix]
    - xorg-libxt  # [linux]

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets
  requires:
    - setuptools

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
