{% set version = "8.1.0" %}
{% set build_number = 4 %}
{% set minor_version = ".".join(version.split(".")[:2]) %}

{% set build_number = build_number + 200 %}   # [not VTK_WITH_OSMESA]

package:
  name: vtk
  version: {{ version }}

source:
  url: http://www.vtk.org/files/release/{{ minor_version }}/VTK-{{ version }}.tar.gz
  fn:  VTK-{{ version }}.tar.gz
  sha256: 6e269f07b64fb13774f5925161fb4e1f379f4e6a0131c8408c555f6b58ef3cb7

build:
  skip: True  # [win and py27]
  number: {{ build_number }}
  features:
    - vc14  # [win and py35]
    - vc14  # [win and py36]
    - mesalib   # [VTK_WITH_OSMESA]

requirements:
  build:
    - toolchain
    - cmake
    - ninja
    - python
    # VTK Third Party dependencies
    - zlib 1.2.11
    - freetype 2.8.1
    - hdf5 1.10.1
    - libxml2 2.9.*
    - libpng >=1.6.32,<1.6.35
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - jsoncpp 1.8.1
    - expat 2.2.*
    - tbb
    - mesalib   # [VTK_WITH_OSMESA]
    - libnetcdf 4.4.*
    - lz4-c
    - libogg     # [unix]
    - libtheora  # [unix]
  run:
    - python
    - future  # used in the generated python wrappers
    # VTK Third Party dependencies
    - zlib 1.2.11
    - freetype 2.8.1
    - hdf5 1.10.1
    - libxml2 2.9.*
    - libpng >=1.6.32,<1.6.35
    - jpeg 9*
    - libtiff >=4.0.8,<4.0.10
    - jsoncpp 1.8.1
    - expat 2.2.*
    - tbb
    - mesalib   # [VTK_WITH_OSMESA]
    - libnetcdf 4.4.*
    - lz4-c
    - libogg     # [unix]
    - libtheora  # [unix]

test:
  imports:
    - vtk
    - vtk.vtkChartsCore
    - vtk.vtkCommonCore
    - vtk.vtkFiltersCore
    - vtk.vtkFiltersGeneric
    - vtk.vtkGeovisCore
    - vtk.vtkFiltersHybrid
    - vtk.vtkIOCore
    - vtk.vtkImagingCore
    - vtk.vtkInfovisCore
    - vtk.vtkRenderingCore
    - vtk.vtkViewsCore
    - vtk.vtkRenderingVolume
    - vtk.vtkInteractionWidgets

about:
  home: http://www.vtk.org/
  license: BSD 3-Clause
  license_file: Copyright.txt
  summary: >
    The Visualization Toolkit (VTK) is an open-source, freely available software
    system for 3D computer graphics, modeling, image processing, volume
    rendering, scientific visualization, and information visualization.

extra:
  recipe-maintainers:
    - Korijn
    - ivoflipse
    - Maxyme
    - ccordoba12
    - grlee77
    - msarahan
    - patricksnape
    - dfroger
    - tadeu
    - marcelotrevisani
